### ISSUE TITLE
decrypt error

### ISSUE THREAD

**Issue by icehan2016** [dabslants/TripleDES#1]
$data = $menc;   // result of encrypted data  array
$key = 'mykey';
$skip = 'date';
**OKEncrypt::encrypt($data, $key);**

**OKEncrypt::decrypt($data, $key);**

**Comment by dabslants** [comment]
Here is the fix. write the result of the encrypt to a variable as shown below;

// decrypt array or string
$data = $enc;   // result of encrypted data string or array
$key = 'mykey';
$enc = OKEncrypt::encrypt($data, $key); // encrypted data

// decrypt array but skip an element
OKEncrypt::decrypt($enc, $key);   // decrypted data
